config/routes.rb
Rails.application.routes.draw do
 
 get "/friend_pages/:id" => "friend_pages#index",as: "my_friend_pages"

  resources :foods_reviews
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  resources :images
  resources :review_foods
  resources :follows
  resources :likes
  post 'likes/check_delete'
  resources :votes
  resources :comments
  resources :reviews
  resources :restaurants
  resources :foods
  resources :mypages
  root 'static_pages#home'
 

  devise_for :users

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :review
    has_many :likes
end

app/models/follow.rb
class Follow < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    # def create
    #     Follow.create(create_params)
    #     redirect_to controller: 'users',action: 'index'
    # end
    
    # def destroy
    #     follow = Follow.find(params[:id])
    #     follow.destroy
    #     redirect_to controller: 'users',action: 'index'
    # end
    
    # private
    
    # def create_params
    #     params.permit(:followed_id).merge(follower_id: current_user.id)
    # end
end

app/models/food.rb
class Food < ActiveRecord::Base
    has_and_belongs_to_many :reviews
    
end

app/models/foods_review.rb
class FoodsReview < ActiveRecord::Base
    belongs_to :food
    belongs_to :review
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file,ImageUploader
    belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :comment
    belongs_to :review
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :reviews
    has_many :votes
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :restaurant
    has_and_belongs_to_many :foods
    has_many :votes
    has_many :likes
    has_many :comments, -> { order "created_at DESC"}
    validates :title,presence: true
    validates :description,presence: true
end

app/models/review_food.rb
class ReviewFood < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :votes
  has_many :active_relationships, class_name:  "Follow",
           foreign_key: "follower_id",
           dependent:   :destroy
  has_many :passive_relationships, class_name:  "Follow",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :likes
  has_many :comments
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates :name,presence: true
#validates :email,presence: true
#validates :password,presence: true
  def following?(other_user)
    following.include?(other_user)
  end
  
  def accurate
    sum = 0
    if reviews.count == 0
      score =0
    else
      reviews.each do |review|
      sum += review.score
      end
      score = sum/reviews.count.to_f
    end
    score
  end
  
  def active
    active = reviews.count
    active
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :review
    belongs_to :restaurant
end

app/controllers/foods_reviews_controller.rb
class FoodsReviewsController < ApplicationController
  before_action :set_foods_review, only: [:show, :edit, :update, :destroy]

  # GET /foods_reviews
  # GET /foods_reviews.json
  def index
    @foods_reviews = FoodsReview.all
  end

  # GET /foods_reviews/1
  # GET /foods_reviews/1.json
  def show
  end

  # GET /foods_reviews/new
  def new
    @foods_review = FoodsReview.new
  end

  # GET /foods_reviews/1/edit
  def edit
  end

  # POST /foods_reviews
  # POST /foods_reviews.json
  def create
    @foods_review = FoodsReview.new(foods_review_params)

    respond_to do |format|
      if @foods_review.save
        format.html { redirect_to @foods_review, notice: 'Foods review was successfully created.' }
        format.json { render :show, status: :created, location: @foods_review }
      else
        format.html { render :new }
        format.json { render json: @foods_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods_reviews/1
  # PATCH/PUT /foods_reviews/1.json
  def update
    respond_to do |format|
      if @foods_review.update(foods_review_params)
        format.html { redirect_to @foods_review, notice: 'Foods review was successfully updated.' }
        format.json { render :show, status: :ok, location: @foods_review }
      else
        format.html { render :edit }
        format.json { render json: @foods_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods_reviews/1
  # DELETE /foods_reviews/1.json
  def destroy
    @foods_review.destroy
    respond_to do |format|
      format.html { redirect_to foods_reviews_url, notice: 'Foods review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foods_review
      @foods_review = FoodsReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foods_review_params
      params.require(:foods_review).permit(:food_id, :review_id)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/foods_reviews_helper.rb
module FoodsReviewsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    user.images.last&.file&.url || 'https://previews.123rf.com/images/stalkerstudent/stalkerstudent1601/stalkerstudent160101173/50961996-user-icon-vector-flat-design-style-eps-10.jpg'
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/foods_reviews/_form.html.erb
<%= form_for(@foods_review) do |f| %>
  <% if @foods_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foods_review.errors.count, "error") %> prohibited this foods_review from being saved:</h2>

      <ul>
      <% @foods_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.number_field :food_id %>
  </div>
  <div class="field">
    <%= f.label :review_id %><br>
    <%= f.number_field :review_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods_reviews/edit.html.erb
<h1>Editing Foods Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @foods_review %> |
<%= link_to 'Back', foods_reviews_path %>

app/views/foods_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods_reviews.each do |foods_review| %>
      <tr>
        <td><%= foods_review.food_id %></td>
        <td><%= foods_review.review_id %></td>
        <td><%= link_to 'Show', foods_review %></td>
        <td><%= link_to 'Edit', edit_foods_review_path(foods_review) %></td>
        <td><%= link_to 'Destroy', foods_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foods review', new_foods_review_path %>

app/views/foods_reviews/new.html.erb
<h1>New Foods Review</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_reviews_path %>

app/views/foods_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @foods_review.food_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @foods_review.review_id %>
</p>

<%= link_to 'Edit', edit_foods_review_path(@foods_review) %> |
<%= link_to 'Back', foods_reviews_path %>