config/routes.rb
Rails.application.routes.draw do
 
 get "/friend_pages/:id" => "friend_pages#index",as: "my_friend_pages"

  resources :foods_reviews
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  resources :images
  resources :review_foods
  resources :follows
  resources :likes
  post 'likes/check_delete'
  resources :votes
  resources :comments
  resources :reviews
  resources :restaurants
  resources :foods
  resources :mypages
  root 'static_pages#home'
 

  devise_for :users

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :review
    has_many :likes
end

app/models/follow.rb
class Follow < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    # def create
    #     Follow.create(create_params)
    #     redirect_to controller: 'users',action: 'index'
    # end
    
    # def destroy
    #     follow = Follow.find(params[:id])
    #     follow.destroy
    #     redirect_to controller: 'users',action: 'index'
    # end
    
    # private
    
    # def create_params
    #     params.permit(:followed_id).merge(follower_id: current_user.id)
    # end
end

app/models/food.rb
class Food < ActiveRecord::Base
    has_and_belongs_to_many :reviews
    
end

app/models/foods_review.rb
class FoodsReview < ActiveRecord::Base
    belongs_to :food
    belongs_to :review
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file,ImageUploader
    belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :comment
    belongs_to :review
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :reviews
    has_many :votes
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :restaurant
    has_and_belongs_to_many :foods
    has_many :votes
    has_many :likes
    has_many :comments, -> { order "created_at DESC"}
    validates :title,presence: true
    validates :description,presence: true
end

app/models/review_food.rb
class ReviewFood < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :votes
  has_many :active_relationships, class_name:  "Follow",
           foreign_key: "follower_id",
           dependent:   :destroy
  has_many :passive_relationships, class_name:  "Follow",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :likes
  has_many :comments
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates :name,presence: true
#validates :email,presence: true
#validates :password,presence: true
  def following?(other_user)
    following.include?(other_user)
  end
  
  def accurate
    sum = 0
    if reviews.count == 0
      score =0
    else
      reviews.each do |review|
      sum += review.score
      end
      score = sum/reviews.count.to_f
    end
    score
  end
  
  def active
    active = reviews.count
    active
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :review
    belongs_to :restaurant
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    user.images.last&.file&.url || 'https://previews.123rf.com/images/stalkerstudent/stalkerstudent1601/stalkerstudent160101173/50961996-user-icon-vector-flat-design-style-eps-10.jpg'
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag 'logo.png', id: 'logo-img' %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <div class="mr-auto">
        <%= form_tag reviews_path, id: 'search-form', class: 'form-inline my-2 my-lg-0', method: :get do %>
          <%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'form-control mr-sm-2' %>
          <%= button_tag nil, class:'btn btn-outline-white my-2 my-sm-0' do %>
            <i class="fa fa-search" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= link_to new_review_path, class: 'btn btn-outline-white' do %>
          <i class="fa fa-plus"></i> Review
      <% end %>
      <% end %>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), id: 'nav-user-icon', class: 'rounded-circle' %>
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'My Page', mypages_path, class: 'dropdown-item' %>
              <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%=link_to "Sign in",new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%=link_to "Sign up",new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>