config/routes.rb
Rails.application.routes.draw do
 
 get "/friend_pages/:id" => "friend_pages#index",as: "my_friend_pages"

  resources :foods_reviews
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  resources :images
  resources :review_foods
  resources :follows
  resources :likes
  post 'likes/check_delete'
  resources :votes
  resources :comments
  resources :reviews
  resources :restaurants
  resources :foods
  resources :mypages
  root 'static_pages#home'
 

  devise_for :users

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :review
    has_many :likes
end

app/models/follow.rb
class Follow < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    # def create
    #     Follow.create(create_params)
    #     redirect_to controller: 'users',action: 'index'
    # end
    
    # def destroy
    #     follow = Follow.find(params[:id])
    #     follow.destroy
    #     redirect_to controller: 'users',action: 'index'
    # end
    
    # private
    
    # def create_params
    #     params.permit(:followed_id).merge(follower_id: current_user.id)
    # end
end

app/models/food.rb
class Food < ActiveRecord::Base
    has_and_belongs_to_many :reviews
    
end

app/models/foods_review.rb
class FoodsReview < ActiveRecord::Base
    belongs_to :food
    belongs_to :review
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file,ImageUploader
    belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :comment
    belongs_to :review
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :reviews
    has_many :votes
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :restaurant
    has_and_belongs_to_many :foods
    has_many :votes
    has_many :likes
    has_many :comments, -> { order "created_at DESC"}
    validates :title,presence: true
    validates :description,presence: true
end

app/models/review_food.rb
class ReviewFood < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :votes
  has_many :active_relationships, class_name:  "Follow",
           foreign_key: "follower_id",
           dependent:   :destroy
  has_many :passive_relationships, class_name:  "Follow",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :likes
  has_many :comments
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates :name,presence: true
#validates :email,presence: true
#validates :password,presence: true
  def following?(other_user)
    following.include?(other_user)
  end
  
  def accurate
    sum = 0
    if reviews.count == 0
      score =0
    else
      reviews.each do |review|
      sum += review.score
      end
      score = sum/reviews.count.to_f
    end
    score
  end
  
  def active
    active = reviews.count
    active
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :user
    belongs_to :review
    belongs_to :restaurant
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = Follow.new
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows
  # POST /follows.json
  def create
    @follow = Follow.new(
      follower_id: current_user.id,
      followed_id: params[:followed_id]
      )

    respond_to do |format|
      if @follow.save
        format.html { redirect_to "/mypages", notice: 'Follow was successfully created.' }
        format.json { render :show, status: :created, location: @follow }
      else
        format.html { render :new }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follows/1
  # PATCH/PUT /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to "/mypages", notice: 'Follow was successfully updated.' }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to "/mypages", notice: 'Follow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user)
    user.images.last&.file&.url || 'https://previews.123rf.com/images/stalkerstudent/stalkerstudent1601/stalkerstudent160101173/50961996-user-icon-vector-flat-design-style-eps-10.jpg'
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br>
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :followed_id %><br>
    <%= f.number_field :followed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Follows</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= follow.follower_id %></td>
        <td><%= follow.followed_id %></td>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @follow.follower_id %>
</p>

<p>
  <strong>Followed:</strong>
  <%= @follow.followed_id %>
</p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>